name: env1
description: Udemy - Dart Advanced course.
version: 0.0.1
author: calebcuthbertlinden <caleblinden@cookiecut.co.za>

environment:
  sdk: '>=1.20.1 <=2.13.3'

dependencies:
  archive: ^3.1.6
  pointycastle: ^3.3.5
  http: ^0.13.3
#  sqljocky5: ^2.2.1

dev_dependencies:
  test: ^1.17.12